/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class EditEmployeeInfo_jFrame extends javax.swing.JFrame {

    
    private MyHashTable mainHT;  // This contains the ref value for theHT of MainJFrame.

    /**
     * Creates new form EditEmployeeInfo_jFrame
     */
    public EditEmployeeInfo_jFrame() {
        initComponents();
        
        resultLabel.setText(" ");

        resultLabel.setPreferredSize(new java.awt.Dimension(22, 300));
        empNumField.setText("");
        empNumField.setPreferredSize(Main_jFrame.TEXT_FIELD_DIMENSION);
        firstNameField.setPreferredSize(Main_jFrame.TEXT_FIELD_DIMENSION);
        lastNameField.setPreferredSize(Main_jFrame.TEXT_FIELD_DIMENSION);
        FTEInternalFrame.setVisible(true);  // Hide the FTE internal jFrame
        PTEInternalFrame.setVisible(true);  // Hide the PTE internal jFrame
        
        salaryField.setPreferredSize(Main_jFrame.TEXT_FIELD_DIMENSION);
        hourlyWageField.setPreferredSize(Main_jFrame.TEXT_FIELD_DIMENSION);
        hoursPerWeekField.setPreferredSize(Main_jFrame.TEXT_FIELD_DIMENSION);
        weeksPerYearField.setPreferredSize(Main_jFrame.TEXT_FIELD_DIMENSION);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    
        
        pack();
        
        FTEInternalFrame.setVisible(false);  // Hide the FTE internal jFrame
        PTEInternalFrame.setVisible(false);  // Hide the PTE internal jFrame
    }

    
    public void setMainHT(MyHashTable theRefVal) {
        mainHT = theRefVal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empTypeGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        empNumField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        saveChangesBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        FTERadioBtn = new javax.swing.JRadioButton();
        PTERadioBtn = new javax.swing.JRadioButton();
        resultLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PTEInternalFrame = new javax.swing.JInternalFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hourlyWageField = new javax.swing.JTextField();
        hoursPerWeekField = new javax.swing.JTextField();
        weeksPerYearField = new javax.swing.JTextField();
        FTEInternalFrame = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        salaryField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        deductRateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Employee Number");

        empNumField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                empNumFieldInputMethodTextChanged(evt);
            }
        });
        empNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNumFieldActionPerformed(evt);
            }
        });
        empNumField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empNumFieldKeyReleased(evt);
            }
        });

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Employee Type");

        saveChangesBtn.setText("Save Changes");
        saveChangesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        empTypeGroup.add(FTERadioBtn);
        FTERadioBtn.setText("FTE");
        FTERadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTERadioBtnActionPerformed(evt);
            }
        });

        empTypeGroup.add(PTERadioBtn);
        PTERadioBtn.setText("PTE");
        PTERadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTERadioBtnActionPerformed(evt);
            }
        });

        resultLabel.setText("jLabel5");

        jLabel5.setText("Tip: Hit return after entering Employee Info to autofill text fields.");

        PTEInternalFrame.setVisible(true);

        jLabel9.setText("Hourly wage");

        jLabel10.setText("Hours per week");

        jLabel11.setText("Weeks per year");

        javax.swing.GroupLayout PTEInternalFrameLayout = new javax.swing.GroupLayout(PTEInternalFrame.getContentPane());
        PTEInternalFrame.getContentPane().setLayout(PTEInternalFrameLayout);
        PTEInternalFrameLayout.setHorizontalGroup(
            PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTEInternalFrameLayout.createSequentialGroup()
                .addGroup(PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTEInternalFrameLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31)
                        .addComponent(hourlyWageField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PTEInternalFrameLayout.createSequentialGroup()
                        .addGroup(PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hoursPerWeekField)
                            .addComponent(weeksPerYearField))))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        PTEInternalFrameLayout.setVerticalGroup(
            PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTEInternalFrameLayout.createSequentialGroup()
                .addGroup(PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(hourlyWageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(hoursPerWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(PTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(weeksPerYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        FTEInternalFrame.setVisible(true);

        jLabel6.setText("Salary");

        salaryField.setToolTipText("Gross Annual Salary");

        javax.swing.GroupLayout FTEInternalFrameLayout = new javax.swing.GroupLayout(FTEInternalFrame.getContentPane());
        FTEInternalFrame.getContentPane().setLayout(FTEInternalFrameLayout);
        FTEInternalFrameLayout.setHorizontalGroup(
            FTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTEInternalFrameLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );
        FTEInternalFrameLayout.setVerticalGroup(
            FTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTEInternalFrameLayout.createSequentialGroup()
                .addGroup(FTEInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 142, Short.MAX_VALUE))
        );

        jLabel7.setText("Deduct Rate");

        deductRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deductRateFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(saveChangesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lastNameField)
                            .addComponent(firstNameField)
                            .addComponent(empNumField)
                            .addComponent(deductRateField))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FTERadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PTERadioBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FTEInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PTEInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(empNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(deductRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FTERadioBtn)
                            .addComponent(PTERadioBtn)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FTEInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PTEInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(resultLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveChangesBtn)
                    .addComponent(exitBtn))
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNumFieldActionPerformed
        resultLabel.setText(" ");
        // Autofills previous info in fields to be edited
        int empNum;
        try{
            empNum = Integer.parseInt(empNumField.getText());
        }
        catch(java.lang.NumberFormatException e){
            resultLabel.setText("Employee number invalid!");
            resultLabel.setVisible(true);
            return;
        }
        // Displays emp info on GUI
        EmployeeInfo theEmp = mainHT.getEmployee(empNum);
        if(theEmp == null){

            resultLabel.setText("Employee #" + empNum + " not found!");
            resultLabel.setVisible(true);
            return;
        }
        firstNameField.setText(theEmp.firstName);
        lastNameField.setText(theEmp.lastName);
        deductRateField.setText(String.valueOf(theEmp.deductRate));
        
        if(theEmp instanceof FTE){
            FTE theFTE = (FTE)theEmp;   // Casts object of super class in subclass FTE
            salaryField.setText(String.valueOf(theFTE.yearlySalary));
        }
        else{
            PTE thePTE = (PTE)theEmp;   // Casts object of super class in subclass FTE
            hourlyWageField.setText(String.valueOf(thePTE.hourlyWage));
            hoursPerWeekField.setText(String.valueOf(thePTE.hoursPerWeek));
            weeksPerYearField.setText(String.valueOf(thePTE.weeksPerYear));
        }
        
       
    }//GEN-LAST:event_empNumFieldActionPerformed

    private void saveChangesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesBtnActionPerformed
        int theEmpNum;
        try{
            theEmpNum = Integer.parseInt(empNumField.getText());
        }
        catch(java.lang.NumberFormatException e){
            resultLabel.setText("Employee number invalid!");
            return;
        }
        // Displays emp info on GUI
        EmployeeInfo theEmp = mainHT.getEmployee(theEmpNum);
        if(theEmp == null){

            resultLabel.setText("Employee #" + theEmpNum + " not found!");
            return;
        }
        
        // Data validation for deductRate
        double theDeductRate;
        try{
            theDeductRate = Double.parseDouble(deductRateField.getText());
            if(theDeductRate < 0 || theDeductRate > 1)  throw new java.lang.NumberFormatException();
        }
        catch(java.lang.NumberFormatException e){
            resultLabel.setText("Deduct rate invalid!");
            return;
        }
        
        String theFirstName = firstNameField.getText();
        String theLastName = lastNameField.getText();
        
        // copied from addnewemp
        // FULL TIME EMPLOYEE
        if (FTERadioBtn.isSelected()) {          
            String strSalary = salaryField.getText();
            double Salary;
            try{
                Salary = Double.parseDouble(strSalary);
            }
            catch(java.lang.NumberFormatException e){
                jLabel4.setText("Employee salary invalid!");
                return;
            }
            FTE theFTE = new FTE(theEmpNum, theFirstName, theLastName,
                        0, 0, theDeductRate, Salary);
            System.out.println("Salary of the FTE is " + Salary);
            mainHT.removeEmployee(theEmpNum);
            mainHT.addEmployee(theFTE);
        }
        
        // PART TIME EMPLOYEE
        else if (PTERadioBtn.isSelected()) {
            // Get the hourly wage, hours per week, weeks per year
            // Instantiate an PTE with the info for that employee
            // Add that employee to the hash table
            double hourlyWage;
            int hoursPerWeek, weeksPerYear;
            
            try{
                hourlyWage = Double.parseDouble(hourlyWageField.getText());
                hoursPerWeek = Integer.parseInt(hoursPerWeekField.getText());
                weeksPerYear = Integer.parseInt(weeksPerYearField.getText());
            }
            catch(java.lang.NumberFormatException e){
                jLabel4.setText("Employee wage info invalid!");
                return;
            }
            mainHT.removeEmployee(theEmpNum);
            mainHT.addEmployee(new PTE(theEmpNum, theFirstName, theLastName,
                        0, 0, theDeductRate, hourlyWage, hoursPerWeek, weeksPerYear));
        }
        // If neither FTE nor PTE was selected notify user to click select one
        else{
            jLabel4.setVisible(true);
            jLabel4.setText(    "MUST SELECT EITHER FTE or PTE!");
            return;
        }
        jLabel4.setText("Added new employee:  " + empNumField.getText() + " "
                        + theFirstName + " " + theLastName);       
        jLabel4.setVisible(true);
        
        empNumField.setText("");
        firstNameField.setText("");
        lastNameField.setText("");
        deductRateField.setText("");

    }//GEN-LAST:event_saveChangesBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void PTERadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTERadioBtnActionPerformed
        FTEInternalFrame.setVisible(false);
        PTEInternalFrame.setVisible(true);
    }//GEN-LAST:event_PTERadioBtnActionPerformed

    private void empNumFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empNumFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_empNumFieldKeyReleased

    private void empNumFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_empNumFieldInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_empNumFieldInputMethodTextChanged

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void FTERadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTERadioBtnActionPerformed
        FTEInternalFrame.setVisible(true);
        PTEInternalFrame.setVisible(false);
    }//GEN-LAST:event_FTERadioBtnActionPerformed

    private void deductRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deductRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deductRateFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeInfo_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeInfo_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeInfo_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeInfo_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployeeInfo_jFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame FTEInternalFrame;
    private javax.swing.JRadioButton FTERadioBtn;
    private javax.swing.JInternalFrame PTEInternalFrame;
    private javax.swing.JRadioButton PTERadioBtn;
    private javax.swing.JTextField deductRateField;
    private javax.swing.JTextField empNumField;
    private javax.swing.ButtonGroup empTypeGroup;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField hourlyWageField;
    private javax.swing.JTextField hoursPerWeekField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField salaryField;
    private javax.swing.JButton saveChangesBtn;
    private javax.swing.JTextField weeksPerYearField;
    // End of variables declaration//GEN-END:variables
}
